[tox]
minversion = 4.0
envlist = style, py311, coverage
isolated_build = true

[testenv:style]
description = Run code style checks with flake8
labels = static
deps = 
    flake8
    flake8-import-order
    flake8-black
    flake8-builtins
    flake8-docstrings
commands = 
    flake8 hyppo/ tests/ {posargs}

[testenv]
description = Run the test suite with coverage reporting
labels = dynamic
deps = 
    pytest
    pytest-cov
setenv =
    COVERAGE_FILE = {toxworkdir}/.coverage.{envname}
commands = pytest tests/ --cov-report= --cov=hyppo --cov-append -vm '' {posargs}


[testenv:coverage]
description = Generate coverage report
labels = dynamic
deps = 
    {[testenv]deps}
    coverage
setenv =
    COVERAGE_FILE = {toxworkdir}/.coverage
depends = py311
commands = 
    coverage combine
    coverage report -m --fail-under 100
